Add VSM config/fs options
Teach xfstests how to run on a VSM node configured with vsm-config.

To run on such a node:

 > git clone git@github.com:/versity/xfstests.git
 > cd xfstests
 > make
 > ln -s local.config.vsm local.config (or just copy it)
 > ./check -g quick

Results are in xfstests/results/

diff --git a/common/config b/common/config
--- a/common/config
+++ b/common/config
@@ -248,6 +248,7 @@ case "$HOSTOS" in
         export MKFS_CIFS_PROG="false"
         export MKFS_OVERLAY_PROG="false"
         export MKFS_REISER4_PROG="`set_prog_path mkfs.reiser4`"
+        export MKFS_SAMFS_PROG="`set_prog_path mkfs.vsm`"
         ;;
 esac
 
@@ -491,13 +492,15 @@ get_next_config() {
 		exit 1
 	fi
 
-	echo $TEST_DEV | grep -qE ":|//" > /dev/null 2>&1
-	if [ ! -b "$TEST_DEV" -a "$?" != "0" -a "$FSTYP" != "overlay" ]; then
-		echo "common/config: Error: \$TEST_DEV ($TEST_DEV) is not a block device or a network filesystem"
-		exit 1
-	elif [ "$FSTYP" == "overlay" -a ! -d "$TEST_DEV" ]; then
-		echo "common/config: Error: \$TEST_DEV ($TEST_DEV) is not a directory for overlay"
-		exit 1
+	if [ "$FSTYP" != "samfs" ]; then
+	    echo $TEST_DEV | grep -qE ":|//" > /dev/null 2>&1
+	    if [ ! -b "$TEST_DEV" -a "$?" != "0" -a "$FSTYP" != "overlay" ]; then
+		    echo "common/config: Error: \$TEST_DEV ($TEST_DEV) is not a block device or a network filesystem"
+			exit 1
+	    elif [ "$FSTYP" == "overlay" -a ! -d "$TEST_DEV" ]; then
+			echo "common/config: Error: \$TEST_DEV ($TEST_DEV) is not a directory for overlay"
+			exit 1
+	    fi
 	fi
 
 	if [ ! -d "$TEST_DIR" ]; then
@@ -517,14 +520,16 @@ get_next_config() {
 		export SCRATCH_DEV_NOT_SET=true
 	fi
 
-	echo $SCRATCH_DEV | grep -qE ":|//" > /dev/null 2>&1
-	if [ ! -z "$SCRATCH_DEV" -a ! -b "$SCRATCH_DEV" -a "$?" != "0" -a "$FSTYP" != "overlay" ]; then
-		echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) is not a block device or a network filesystem"
-		exit 1
-	elif [ ! -z "$SCRATCH_DEV" -a "$FSTYP" == "overlay" -a ! -d "$SCRATCH_DEV" ]; then
-		echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) is not a directory for overlay"
-		exit 1
-	fi
+	if [ "$FSTYP" != "samfs" ]; then
+		echo $SCRATCH_DEV | grep -qE ":|//" > /dev/null 2>&1
+		if [ ! -z "$SCRATCH_DEV" -a ! -b "$SCRATCH_DEV" -a "$?" != "0" -a "$FSTYP" != "overlay" ]; then
+			echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) is not a block device or a network filesystem"
+			exit 1
+		elif [ ! -z "$SCRATCH_DEV" -a "$FSTYP" == "overlay" -a ! -d "$SCRATCH_DEV" ]; then
+			echo "common/config: Error: \$SCRATCH_DEV ($SCRATCH_DEV) is not a directory for overlay"
+			exit 1
+		fi
+    fi
 
 	if [ ! -z "$SCRATCH_MNT" -a ! -d "$SCRATCH_MNT" ]; then
 		echo "common/config: Error: \$SCRATCH_MNT ($SCRATCH_MNT) is not a directory"
